### ISSUE TITLE
Wrong model field

### ISSUE THREAD

**Issue by rockroman** [rockroman/CI_PP5_Blade#45]
Describe the Bug:
while trying to implement timesince feature to product reviews 
The "time posted" review model field was given value :"timeField" and the feature couldn't be implemented without
overriding model field that was unnecessary. 

 Solution:
time posted field was changed to:
 `time_posted = models.DateTimeField(auto_now_add=True)`
and timesince feature was implemented

**Comment by NikilTn** [comment]
hi, @rockroman, I'm starting my open-source journey with Django (actively following [wagtail](https://github.com/wagtail/wagtail)). I want to contribute to [CI_PP5__Blade](https://github.com/rockroman/CI_PP5_Blade) and learn new things, can you give me a brief intro like how things are done here and add me as a contributor if possible 😊.
